name: Release

on:
  push:
    branches:
      - '*'

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: 'Checkout the JDK source'
        uses: actions/checkout@v4

      - name: 'Set up JDK 11 Temurin'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Java version
        run: java -version

      - name: Install MSYS2
        run: choco install msys2 --no-progress

      # - name: Add MSYS2 to PATH
      #   shell: bash
      #   run: |
      #     ls /c/tools
      #     ls /c/tools/msys64
      #     # "/c/tools/msys64" >> $PATH
      #     export PATH="/c/tools/msys64/usr/bin:$PATH"

      - name: Set up MSYS2 environment
        shell: bash
        run: |
          export PATH="/c/tools/msys64/usr/bin:$PATH"
          env
          bash --login -i -c "pacman -Syu --noconfirm"  # Update package database
          bash --login -i -c "pacman -S --noconfirm make gcc coreutils"  # Install make, gcc, coreutils
          ls /c/tools/msys64/usr/include/sys

      - name: 'Download libjdk.lib'
        uses: robinraju/release-downloader@v1
        with:
          repository: 'gluonhq/mobile'
          latest: true
          fileName: 'windows-x64.zip'

      - name: 'Build'
        run: |
          powershell -Command "Expand-Archive -Path windows-x64.zip -DestinationPath C:\temp\"
          powershell -Command "Move-Item -Path C:\temp\windows-x64\libjdk.lib -Destination C:\temp\"
          ls C:\temp\
          ls
          export PATH="/c/tools/msys64/usr/bin:$PATH"
          bash --login -i -c "make clean all"

      - name: 'Upload static image artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vmone-windows-x64
          path: C:\temp\lib\windows\x64\staticjdk\lib\
          retention-days: 1

  release:
    needs: [
        build-windows-x64
    ]
    runs-on: ubuntu-22.04
    steps:
      - name: Download windows x64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: vmone-windows-x64
          path: ./dist/windows-x64/lib/

      - name: Zip downloaded artifacts
        run: |
          cd $GITHUB_WORKSPACE/dist/windows-x64/
          zip -r ../vmone-windows-x64.zip lib/
      
      - name: Check zip files
        run: |
          ls -R ./dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*.zip
