name: Release

on:
  push:
    branches:
      - '*'

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: 'Checkout the JDK source'
        uses: actions/checkout@v4
      - name: 'Set up JDK 11 Temurin'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          architecture: 'x64'
      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            gcc
            coreutils
      - name: 'Download libjdk.lib'
        uses: robinraju/release-downloader@v1
        with:
          repository: 'gluonhq/mobile'
          latest: true
          fileName: 'windows-x64.zip'
      - name: 'Build Copy'
        shell: msys2 {0}
        run: |
          mkdir -p /c/temp
          unzip windows-x64.zip -d /c/temp
          mv /c/temp/windows-x64/libjdk.lib /c/temp/
          export JAVA_HOME="/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/11.0.24-8/x64"
          export PATH="$JAVA_HOME/bin:$PATH"
          make clean all
      - name: 'Upload static image artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vmone-windows-x64
          path: lib\windows\staticjdk\lib\
          retention-days: 1

  release:
    needs: [
        build-windows-x64
    ]
    runs-on: ubuntu-22.04
    steps:
      - name: Download windows x64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: vmone-windows-x64
          path: ./dist/windows-x64/lib/

      - name: Zip downloaded artifacts
        run: |
          cd $GITHUB_WORKSPACE/dist/windows-x64/
          zip -r ../vmone-windows-x64.zip lib/
      
      - name: Check zip files
        run: |
          ls -R ./dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*.zip
